### ISSUE TITLE
Possible releases ROM image?

### ISSUE THREAD

**Issue by gbraad** [benryves/BBCBasicSMS#1]
Hi, would it be possible to publish a ROM image?

**Comment by benryves** [comment]
Possible, yes, but to publish one would assume there was something worth releasing in the first place! As this is a rough experiment and absolutely not intended for release I'm afraid I will not publish a ROM image at this stage.

If you want to built it yourself you can do so with [Brass 3](https://github.com/benryves/Brass3/releases), once installed double-click the "Master System BASIC.brassproj" to open it in the project builder and click Build->Rebuild. This will output "Master System BASIC.smsc" in the project's own directory.
